### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by ppolyanskiyy**
Ticket issue link : [LTW2-99](https://lnu-team-work0-2021.atlassian.net/browse/LTW2-99)
💋💖💕❤🥰😘😍

### CODE REVIEW

**Review by SwaTiK4931 — APPROVED** [review]

**Review by loburyaka — COMMENTED** [review]
so bad delete unity thank you in advance)0))

**Comment by ppolyanskiyy** [comment]
> so bad delete unity thank you in advance)0))

okay, thank you. I have already deleted it, and now i'm writing code in Notepad and make animations in Paint 
(❁´◡`❁)

**Comment by loburyaka** [comment]
> > so bad delete unity thank you in advance)0))
> 
> okay, thank you. I have already deleted it, and now i'm writing code in Notepad and make animations in Paint
> (❁´◡`❁)

yes, thank you for that, but now delete windows and sell your laptop on olx, thank you in advance again)0))

**Comment by ppolyanskiyy** [comment]
> > > so bad delete unity thank you in advance)0))
> > 
> > 
> > okay, thank you. I have already deleted it, and now i'm writing code in Notepad and make animations in Paint
> > (❁´◡`❁)
> 
> yes, thank you for that, but now delete windows and sell your laptop on olx, thank you in advance again)0))

shure! i have already sold my laptop on OLX and now i'm writing code on printer with Kali Linux Mac OS
(●'◡'●)

**Comment by loburyaka** [comment]
> > > > so bad delete unity thank you in advance)0))
> > > 
> > > 
> > > okay, thank you. I have already deleted it, and now i'm writing code in Notepad and make animations in Paint
> > > (❁´◡`❁)
> > 
> > 
> > yes, thank you for that, but now delete windows and sell your laptop on olx, thank you in advance again)0))
> 
> shure! i have already sold my laptop on OLX and now i'm writing code on printer with Kali Linux Mac OS

yes, that's cool, but now leave Ukraine and go to India, to write on Assembler, and later switch to coding with 0 and 1 and i expect to see your result in 1 minute and if you don't that, i will fire you from the project, thank you in advance again and again)0))

**Comment by ppolyanskiyy** [comment]
> > > > > so bad delete unity thank you in advance)0))
> > > > 
> > > > 
> > > > okay, thank you. I have already deleted it, and now i'm writing code in Notepad and make animations in Paint
> > > > (❁´◡`❁)
> > > 
> > > 
> > > yes, thank you for that, but now delete windows and sell your laptop on olx, thank you in advance again)0))
> > 
> > 
> > shure! i have already sold my laptop on OLX and now i'm writing code on printer with Kali Linux Mac OS
> 
> yes, that's cool, but now leave Ukraine and go to India, to write on Assembler, and later switch to coding with 0 and 1 and i expect to see your result in 1 minute and if you don't that, i will fire you from the project, thank you in advance again and again)0))

image

**Comment by loburyaka** [comment]
> > > > > > so bad delete unity thank you in advance)0))
> > > > > 
> > > > > 
> > > > > okay, thank you. I have already deleted it, and now i'm writing code in Notepad and make animations in Paint
> > > > > (❁´◡`❁)
> > > > 
> > > > 
> > > > yes, thank you for that, but now delete windows and sell your laptop on olx, thank you in advance again)0))
> > > 
> > > 
> > > shure! i have already sold my laptop on OLX and now i'm writing code on printer with Kali Linux Mac OS
> > 
> > 
> > yes, that's cool, but now leave Ukraine and go to India, to write on Assembler, and later switch to coding with 0 and 1 and i expect to see your result in 1 minute and if you don't that, i will fire you from the project, thank you in advance again and again)0))
> 
> image

image

**Comment by ppolyanskiyy** [comment]
> > > > > > > so bad delete unity thank you in advance)0))
> > > > > > 
> > > > > > 
> > > > > > okay, thank you. I have already deleted it, and now i'm writing code in Notepad and make animations in Paint
> > > > > > (❁´◡`❁)
> > > > > 
> > > > > 
> > > > > yes, thank you for that, but now delete windows and sell your laptop on olx, thank you in advance again)0))
> > > > 
> > > > 
> > > > shure! i have already sold my laptop on OLX and now i'm writing code on printer with Kali Linux Mac OS
> > > 
> > > 
> > > yes, that's cool, but now leave Ukraine and go to India, to write on Assembler, and later switch to coding with 0 and 1 and i expect to see your result in 1 minute and if you don't that, i will fire you from the project, thank you in advance again and again)0))
> > 
> > 
> > image
> 
> image

image

**Comment by loburyaka** [comment]
> > > > > > > > so bad delete unity thank you in advance)0))
> > > > > > > 
> > > > > > > 
> > > > > > > okay, thank you. I have already deleted it, and now i'm writing code in Notepad and make animations in Paint
> > > > > > > (❁´◡`❁)
> > > > > > 
> > > > > > 
> > > > > > yes, thank you for that, but now delete windows and sell your laptop on olx, thank you in advance again)0))
> > > > > 
> > > > > 
> > > > > shure! i have already sold my laptop on OLX and now i'm writing code on printer with Kali Linux Mac OS
> > > > 
> > > > 
> > > > yes, that's cool, but now leave Ukraine and go to India, to write on Assembler, and later switch to coding with 0 and 1 and i expect to see your result in 1 minute and if you don't that, i will fire you from the project, thank you in advance again and again)0))
> > > 
> > > 
> > > image
> > 
> > 
> > image
> 
> image

image

**Comment by ppolyanskiyy** [comment]
approve, pwease 
ಠ_ಠ

**Comment by loburyaka** [comment]
> approve, pwease
> ಠ_ಠ

no

**Comment by ppolyanskiyy** [comment]
> > approve, pwease
> > ಠ_ಠ
> 
> no

image
yes

**Comment by loburyaka** [comment]
> > > approve, pwease
> > > ಠ_ಠ
> > 
> > 
> > no
> 
> image
> yes

image
no

**Review by loburyaka — APPROVED** [review]
So good so innovative.

**Pull request merged**
